## TOC
- numpy arrays
  - np.array()
  - np.arange(1,10,2) # like range(1,10,2)
  - np.linspace(start, end, num_of_el)
  - indexing and slicing
- multidimensional arrays
  - np.array().shape attribute
  - np.array().reshape(array1_len, array2_len)
- masking

  

In [30]:
# the following line is jupyter notebook specific 
%matplotlib inline

The following introduction to NumPy is based on the following article:
    http://www.datadependence.com/2016/05/scientific-python-numpy/
    
For futher details refer to the official quickstart documentation:
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

# Initialization of NumPy Arrays

You can initialize a one-dimensional NumPy array, for example, by passing a list or a tuple to `np.array`.

In [31]:
import numpy as np


a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))

print(a)
print(b)
#np.arange?

[0 1 2 3 4]
[0 1 2 3 4]


Alternatively, you can create a one-dimensional NumPy array with the `np.arange` function, which is similar to its counterpart `range` in the standard library. Read it's documentation with `np.arange?`.

In [39]:
c = np.arange(9, 30, 4)
print(np.arange(5))
d = list(range(9, 30, 3))
print(c)
print(list(c))
print(d)


[0 1 2 3 4]
[ 9 13 17 21 25 29]
[9, 13, 17, 21, 25, 29]
[9, 12, 15, 18, 21, 24, 27]


Similar to `np.arange`, `np.linspace` creates an array of evenly spaced numbers over a specified interval.

In [33]:
pi_steps = np.linspace(0, 2 * np.pi, 5) # args: start, end, number of elements to produce. returns array of number of elements evenly spaced between start and end.
print(pi_steps)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


## Indexing Elements

In [34]:
print(c)
print(c[0])  # Get element at index position 0
print(c[1])  # Get element at index position 1
print(c[2:6])  # Get subarray from index pos. 2 to excluding index pos. 6
print(c[1:-1:2])  # Get every second element from subarray (omitting first and last)

[ 9 13 17 21 25 29]
9
13
[17 21 25 29]
[13 21]


# Multi-Dimensional Arrays

You can initialize multi-dimensional arrays either explicitely as in the following.

In [35]:
two_dim = np.array([[ 0,  1,  2,  3],
                    [ 4,  5,  6,  7],
                    [ 8,  9, 10, 11]])

three_dim = np.array([[[ 0,  1,  2,  3],
                       [ 4,  5,  6,  7],
                       [ 8,  9, 10, 11]],

                      [[12, 13, 14, 15],
                       [16, 17, 18, 19],
                       [20, 21, 22, 23]],

                      [[24, 25, 26, 27],
                       [28, 29, 30, 31],
                       [32, 33, 34, 35]]])
print(two_dim.shape)
print(three_dim.shape)

(3, 4)
(3, 3, 4)


Or you create a one-dimensional array, which you `reshape` into the desired form.

In [36]:
#a = np.arange(11, 36), array fra 11 til 35
#reshape(5, 5), todimensionel array, 5 på den ene led, 5 på den anden  
#en array kan kun omformes så alle dens indexer passer til den nye format, array længde skal kunne deles i reshape(y,x)
#y arrays af x længde
#np.arange(1, 21).reshape(5, 4)#: 4 arrays af 5 indexer,  np.arange(1, 21).reshape(5, 4): 5 arrays af 4 indexer 
np.arange(11, 36).reshape(5, 5)
#np.arange(1, 10).reshape(3, 3) 
#a = np.arange(1, 21).reshape(4, 5)

print(a)
print(a[0, 2]) # print the 3 value of the first subarray
print(a.shape)
np.arange(12).reshape(3, 4)

[0 1 2 3 4]


IndexError: too many indices for array

In [ ]:
import numpy as np

a = np.arange(11, 36)
print(a)

When defining shapes the shape coordinates are given in the order '*y*', '*x*' for two-dimensional arrays, '*z*', '*y*', '*x*' for three-dimensional arrays, and so on.

In [ ]:
#reshape i 3 dimensioner 
a = np.arange(60).reshape((4,3,5)) # z=4,y=3,x=5 
print(a)
print(a.shape)

## Indexing Elements of Multi-dimensional Arrays

  * How does one create a 2D-array as in the following with NumPy?
  * How to select the highlighted data?

![slicing_img](images/numpy_2D_slicing_diagram_task.png)

In [ ]:
#tal1:tal2
#der tages fra tal1 til tal2

a = np.arange(11, 36).reshape(5, 5)
#a[array, position1:position2]
#vælg først hvilken array(s) man skal have tal fra, og så hvilke indexer i denne array(s)
#::2, hver anden
#::3, hver tredje
#print(a)
# explanation: comma separates the arrays and colon does the positional selection
# 2dArray[rows, columns]
# double colon: get every n^th value e.g. ::2 menas print every second value and 2::3 means get every third value starting from third pos.
red    = a[0, 1:4]  # get one-dim. subarray of row 0, start:1 (pos=2) end:4 (not included, pos=4)
blue   = a[1:4, 0]  # get one-dim. subarrays (index 1,2,3) of column 0
green  = a[::2,::2] # get a two-dim. subarray of every second element by row and column
#::2, hele array, hvert andet index
#::3, hele array, hvert tredje index
purple = a[:, 1]    # get the second column
yellow = a[:-1, :-1]

print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\npurple:',purple,'\nyellow:',yellow)

### Class exercise: table
![](images/numpy_slice_ex.png)
- on the above image find the 3 different slicings using only the array slicing notation

In [ ]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)

yellow = a[0, 0]
print("yellow: \n", yellow)

darkBlue = a[::2, 4]
print("dark blue: \n", darkBlue)

blue = a[:, 1::2]
print("blue\n", blue)

red=a[0, 1:4]
print("red\n", red)

### 3D
reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](images/cube.png)

In [ ]:
import numpy as np

a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
print('whole cube: \n',a, '\n---------------')

#a[0,0,:], øverste række af x, y og z er 0
#a[0,:,:], 0-8, z er 0

print('1st row (x-values): \n',a[0,0,:],'\n---------')
print('1st collumn (y-values, where x==0): \n',a[0,:,0],'\n---------')
print('1st depth (z-values, where y==0 and x==0): \n',a[:,0,0],'\n---------')
print('value of first side, second slice, third piece:\n',a[0, 1, 2], '\n-------------')  # equal to a[0][1][2] = 5
print('values of all x*z where y=2\n',a[:,2], '\n----------')  # equivivalent to a[:,2,:] all z, y=2, all x.
print('all z and y values where x = 2: \n',a[:,:,2], '\n--------')  # 
print('skip each second z,y,x: \n',a[::2,::2,::2])  # all z (skip each second) and all y (skip each second) etc.

### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [ ]:
%load_ext autoreload
%autoreload 2
# %aimport solutions.numpy_ex
from solutions import numpy_ex as nump
nump.cube_ex()

In [ ]:
import numpy as np

a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
print('whole cube: \n',a, '\n---------------')

print("Her printes 12, 13 og 14:", a[1, 1, :])
print("Her printes 3, 12, 21: ", a[:, 1, 0])
print("Her printes hvor z er 0, alt y og x er 2:", a[0, :, 2])

### Properties of the numpy array

In [ ]:
a = np.arange(10, 70, dtype=np.int8).reshape((4,3,5))

print('type: ',type(a))
print('dtype',a.dtype)
print('size',a.size)
print('shape',a.shape)
print('itemsize: ',a.itemsize)
print('ndim: ',a.ndim)
print('nbytes: ',a.nbytes)

## Basic Operators

In [ ]:
# np.ones()
a = np.ones((3, 3))
print(a, '\n-------------')
a[1] = 2 # asign value to multiple cells
a[2] = 3
b = np.arange(9).reshape(3, 3)

print(a)
print(b)

In [ ]:
a = np.ones((3, 3), dtype=int)
a[1] = 2
a[2] = 3
b = np.arange(9).reshape(3, 3)

print('a: \n',a)
print('b: \n',b) 

print('a+b: \n',a + b) # sum values on each index

In [ ]:
print(a - b)

In [ ]:
print(a * b)

In [ ]:
print(b / a)

In [ ]:
print(a ** 2)

In [ ]:
print(a < b)

In [ ]:
print(a > b)

In [ ]:
array_a = np.array([1,2,3]) 
array_b = np.array([4,5,6]) 

print('adding all the products a[0,0]*b[0,0]+a[1,0]*b[1,0]...\n'
      ,np.dot(array_a, array_b))

print('adding all the products a[0,0]*b[0,0]+a[1,0]*b[1,0]...\n'
      ,array_a.dot(array_b))


In [ ]:
print(a)

print("den første:\n", a[1:4,:]==a[1:4])
print(a[1:4].sum())
print(a.cumsum()) #cumulated sum
print(a.min())
print(a.max())

## Fancy Indexing



In [ ]:
# use one np array as indices for another
a = np.arange(0, 100, 10)
indices = np.array([1, 5, -1])
print(indices)
print(a)
print(a[indices])

## Boolean masking is useful
retrieving only the numbers that matches the condition. The mask is a condition
and `a[mask]` is the part of a[] that matches the condition.



In [ ]:
# X=Having 50 values between 0-2*pi, Y=sinus values to x
import matplotlib.pyplot as plt
import numpy as np

#xs = np.array(len(range(60)))

xs = np.linspace(0, 2 * np.pi, 50)
ys = np.sin(xs)
#print(xs,'\n',ys, '\n',len(ys))
plt.plot(xs, ys)

In [ ]:
mask = ys >= 0                        # condition for the blue crosses
plt.plot(xs[mask], ys[mask], 'bx')    # rendering the blue plots only with filtered values
mask = (ys < 0)                       # condition for the green dots
plt.plot(xs[mask], ys[mask], 'go')    # condition applied to xs and ys data sets
plt.show()

## Incomplete Indexing

As you saw above, you can omit index numbers, which then default to index 0 or index for the last element of the array.

In [ ]:
#np.where?

a = np.arange(0, 100, 10)
b = a[:5]                       # when first index is 0 we can omit it.
c = a[a >= 50]                  # mask provided to filter all values below 50
d = a[(a%20 == 0) & (a != 40)]  # more complex conditinal mask
e = np.where((a%20 == 0) & (a != 40), a, None) # mask condition like ternary operator
print('a:\n',a,'\nb:\n',b,'\n:c\n',c,'\nd:\n',d,'\ne:\n',e)


## Where

the `where()` function is another useful way of retrieving elements of an array conditionally. Simply pass it a condition and it will return a tuple of lists of elements where that condition is true.

In [ ]:
import numpy as np

a = np.arange(0, 100, 10)
print(a)
a = np.arange(0, 100, 10)
b = np.where(a < 50)     # returns a tuple
c = np.where(a >= 50)[0] # returns an array (first element of the tuple is the data array)

print('a contains all values: ',a)
print('b contains the indices of the filtered values: ',b,type(b))
print('c contains the filtered values: in',c,type(c))
print('using the indices returned by np.where to get the values:\n',a[c])

### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6
  - using the operators: `%` and `|` mask to only get numbers that are divisible by 3 and numbers begining with 8


In [8]:
import numpy as np
import re

#even numbers only
data = np.arange(1,101).reshape(10,10)
#print(data)

evenData = data[data%2 == 0]
#print(evenData)

sixData = data[data%10 == 6]
#sixData = np.where(data%10 == 6)[0]
print(sixData)

#giver fejl på grund af |
#https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous
#divThreeBeginEight = data[data%3==0 | data%2 == 8]

[ 6 16 26 36 46 56 66 76 86 96]


# Why do we care about NumPy?

Because we want to get things done. As you remember from the last session *Intro to Plotting.ipynb*, we had to write quite a bit of code to compute the histograms for the age distribution within Copenhagen citizens per year.

By representing our input data as a matrix, i.e., a two-dimensional array, and using boolean indexing, we can generate for example the histograms way more concisely and with way fewer lines of code.

In the following we use Pandas, to import the CSV file with the statistics about Copenhagen citizens and we convert the read data into a numpy matrix. We will have a closer look on the  Pandas library in the next session.

In [9]:
%%bash
head befkbhalderstatkode.csv

AAR,BYDEL,ALDER,STATKODE,PERSONER
2015,1,0,5100,614
2015,1,0,5104,2
2015,1,0,5106,1
2015,1,0,5110,1
2015,1,0,5120,4
2015,1,0,5126,1
2015,1,0,5130,5
2015,1,0,5140,3
2015,1,0,5150,5


In [10]:
filename = './befkbhalderstatkode.csv'

#np.genfromtxt?

bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
print(type(bef_stats_df),' of size: ',bef_stats_df.size)
print('The skip_header=1 means that we have only the data\n\nfirst line:\n',bef_stats_df[0],'\nlast line\n',bef_stats_df[len(bef_stats_df)-1])

<class 'numpy.ndarray'>  of size:  2712585
The skip_header=1 means that we have only the data

first line:
 [2015    1    0 5100  614] 
last line
 [1992   99   93 5100    1]


In [12]:
dd = bef_stats_df
mask = (dd[:,0] == 1998) # for all rows filter column/index = 0 to be 1998
dd[mask]

array([[1998,    1,    0, 5100,  500],
       [1998,    1,    0, 5106,    3],
       [1998,    1,    0, 5110,    5],
       ...,
       [1998,   99,   85, 5100,    1],
       [1998,   99,   91, 5100,    1],
       [1998,   99,   99, 5100,    1]], dtype=uint32)

### Amount of 18 years old Danes in CPH?

For example, how can we quickly compute the amount of all Danes (`STATKODE == 5100`) with age 18 in all neighbourhoods for the year 2015?

We just collect that data by expressing it as a conjunction of constraints and subsequently sum it up.


In [13]:
mask = (dd[:,0] == 2015) & (dd[:,2] == 18) & (dd[:,3] == 5100)
print(dd[mask])
#plt.axis([0,10,300,600])
#plt.bar(dd[:,1], dd[:,4])
np.sum(dd[mask][:,4])
#plt.show()

[[2015    1   18 5100  378]
 [2015    2   18 5100  577]
 [2015    3   18 5100  513]
 [2015    4   18 5100  309]
 [2015    5   18 5100  428]
 [2015    6   18 5100  349]
 [2015    7   18 5100  406]
 [2015    8   18 5100  339]
 [2015    9   18 5100  359]
 [2015   10   18 5100  424]
 [2015   99   18 5100   20]]


4102

### Distribution of French and Germans in CPH?


Similarly, in which neighbourhood lifed the most Frenchmen and Germans respectively in 2015?

The following dictionary of neighbourhood codes is created from the explanatory text on the municipalities homepage.

In [14]:
neighb = {1: 'Indre By', 2: 'Østerbro', 3: 'Nørrebro', 4: 'Vesterbro/Kgs. Enghave', 
          5: 'Valby', 6: 'Vanløse', 7: 'Brønshøj-Husum', 8: 'Bispebjerg', 9: 'Amager Øst', 
          10: 'Amager Vest', 99: 'Udenfor'}

In [15]:
def number_of_people_per_neighbourhood(n, mask):
    all_people_in_given_n = dd[mask & (dd[:,1] == n)] #tag alle folk i nabolag med der givne nummer
    sum_of_people = all_people_in_given_n[:,4].sum() # antallet af personer i alle rækker
    return sum_of_people

In [16]:
french_mask = (dd[:,0] == 2015) & (dd[:,3] == 5130)
german_mask = (dd[:,0] == 2015) & (dd[:,3] == 5180)

french = np.array([number_of_people_per_neighbourhood(n, french_mask) for n in neighb.keys()])
print(french)
print(french.sum())
germans = np.array([number_of_people_per_neighbourhood(n, german_mask) for n in neighb.keys()])
print(germans)
print(germans.sum())

[346 337 305 325 133  85  65 135 155 243  27]
2156
[544 557 653 474 258 166 197 314 372 460  26]
4021


In [ ]:
import numpy as np

index_max_fr = np.argmax(french) #index for max argument, 0 
index_max_de = np.argmax(germans)

print(index_max_fr)
print(index_max_de)
print(list(neighb.keys())[index_max_fr])

msg = 'The majority of {} {} are living in {}'
french_neighbourhood_index = list(neighb.keys())[index_max_fr]
print(msg.format(french.max(), 'Frenchmen', neighb[french_neighbourhood_index]))
print(msg.format(germans.max(), 'Germans', neighb[list(neighb.keys())[index_max_de]]))

### From which country came the most imigrants in 2015?

Popular belief says that most imigrants come somewhere from the middle-east. But is it true?

To answer this question, convert the cuntry code data from Danmarks Statistik (http://www.dst.dk/da/Statistik/dokumentation/Times/forebyggelsesregistret/statkode.aspx) into a Python dictionary.

In [ ]:
country_codes = {0: 'Uoplyst (1)', 5001: 'Uoplyst (2)', 5100: 'Danmark', 5101: 'Grønland', 
                 5102: 'Udlandet uoplyst', 5103: 'Statsløs', 5104: 'Finland', 
                 5105: 'Island, ligeret dansk', 5106: 'Island', 5107: 'Liechtenstein', 
                 5108: 'Luxembourg', 5109: 'Monaco', 5110: 'Norge', 5114: 'Europa uoplyst', 
                 5115: 'Kongelig', 5120: 'Sverige', 5122: 'Albanien', 5124: 'Andorra', 
                 5126: 'Belgien', 5128: 'Bulgarien', 5129: 'Tjekkoslovakiet', 
                 5130: 'Frankrig', 5134: 'Grækenland', 5140: 'Nederlandene', 
                 5142: 'Irland', 5150: 'Italien', 5151: 'Serbien og Montenegro', 
                 5152: 'Jugoslavien', 5153: 'Malta', 5154: 'Polen', 5156: 'Portugal', 
                 5158: 'Rumænien', 5159: 'San Marino', 5160: 'Schweiz', 
                 5162: 'Sovjetunionen', 5164: 'Spanien', 5170: 'Storbritannien', 
                 5172: 'Tyrkiet', 5174: 'Ungarn', 5176: 'Vatikanstaten', 5180: 'Tyskland', 
                 5182: 'Østrig', 5199: 'Europa uoplyst', 5202: 'Algeriet', 5204: 'Angola', 
                 5207: 'Botswana', 5213: 'Burundi', 5214: 'Etiopien', 5215: 'Comorerne', 
                 5216: 'Eritrea', 5222: 'Gambia', 5228: 'Ghana', 5230: 'Ækvatorialguinea', 
                 5231: 'Guinea-Bissau', 5232: 'Guinea', 5233: 'Kap Verde', 5234: 'Kenya', 
                 5235: 'Lesotho', 5236: 'Liberia', 5238: 'Libyen', 5240: 'Mozambique', 
                 5242: 'Madagaskar', 5243: 'Mali', 5244: 'Marokko', 5245: 'Mauritius', 
                 5246: 'Nigeria', 5247: 'Namibia', 5248: 'Marshalløerne', 
                 5255: 'Sierra Leone', 5258: 'Sudan', 5259: 'Swaziland', 5260: 'Sydsudan', 
                 5262: 'Sydafrika', 5266: 'Tanzania', 5268: 'Tunesien', 5269: 'Uganda', 
                 5272: 'Egypten', 5273: 'Tuvalu', 5274: 'Kiribati', 5275: 'Vanuatu', 
                 5276: 'Centralafrikanske Republik', 5277: 'Cameroun', 
                 5278: 'Congo, Demokratiske Republik', 5279: 'Congo, Republikken', 
                 5281: 'Benin', 5282: 'Elfenbenskysten', 5283: 'Gabon', 5284: 'Mauretanien', 
                 5285: 'Niger', 5287: 'Rwanda', 5288: 'Senegal', 5289: 'Somalia', 
                 5292: 'Tchad', 5293: 'Togo', 5294: 'Burkina Faso', 5295: 'Zimbabwe', 
                 5296: 'Zambia', 5297: 'Malawi', 5298: 'Seychellerne', 
                 5299: 'Afrika uoplyst', 5302: 'Argentina', 5303: 'Bahamas', 
                 5304: 'Bolivia', 5305: 'Barbados', 5306: 'Brasilien', 5308: 'Guyana', 
                 5309: 'Antigua og Barbuda', 5310: 'Nauru', 
                 5311: 'Skt. Vincent og Grenadinerne', 5314: 'Canada', 5316: 'Chile', 
                 5318: 'Colombia', 5319: 'Syd- og Mellemamerika uoplyst', 
                 5322: 'Costa Rica', 5324: 'Cuba', 5326: 'Dominikanske Republik', 
                 5328: 'Ecuador', 5338: 'Guatemala', 5339: 'Grenada', 5342: 'Haiti', 
                 5344: 'Surinam', 5345: 'Dominica', 5347: 'Skt. Lucia', 5348: 'Honduras', 
                 5352: 'Jamaica', 5354: 'Mexico', 5356: 'Nicaragua', 5358: 'Panama', 
                 5364: 'Paraguay', 5366: 'Peru', 5372: 'El Salvador', 
                 5374: 'Trinidad og Tobago', 5376: 'Uruguay', 5390: 'USA', 
                 5392: 'Venezuela', 5395: 'Vestindiske Øer', 5397: 'Nordamerika uoplyst', 
                 5398: 'Syd- og Mellemamerika uoplyst', 5402: 'Yemen', 
                 5403: 'Forenede Arabiske Emirater', 5404: 'Afghanistan', 5406: 'Bahrain', 
                 5408: 'Bhutan', 5410: 'Bangladesh', 5412: 'Brunei', 5414: 'Myanmar', 
                 5416: 'Cambodja', 5418: 'Sri Lanka', 5422: 'Cypern', 5424: 'Taiwan', 
                 5432: 'Indien', 5434: 'Indonesien', 5435: 'Østtimor', 5436: 'Irak', 
                 5438: 'Iran', 5442: 'Israel', 5444: 'Japan', 5446: 'Jordan', 5448: 'Kina', 
                 5452: 'Kuwait', 5454: 'Laos', 5456: 'Libanon', 5457: 'Maldiverne', 
                 5458: 'Malaysia', 5459: 'Mongoliet', 5462: 'Oman', 5464: 'Nepal', 
                 5466: 'Nordkorea', 5468: 'Vietnam (1)', 5471: 'Asien uoplyst', 
                 5472: 'Pakistan', 5474: 'Filippinerne', 5478: 'Saudi-Arabien', 
                 5482: 'Singapore', 5484: 'Sydkorea', 5486: 'Syrien', 
                 5487: 'Mellemøsten uoplyst', 5488: 'Vietnam (2)', 5492: 'Thailand', 
                 5496: 'Qatar', 5499: 'Asien uoplyst', 5502: 'Australien', 5505: 'Tonga', 
                 5508: 'Fiji', 5514: 'New Zealand', 5522: 'Samoa', 5525: 'Djibouti', 
                 5526: 'Belize', 5534: 'Papua Ny Guinea', 5599: 'Øer i Stillehavet', 
                 5607: 'Estland', 5609: 'Letland', 5611: 'Litauen', 
                 5621: 'Sao Tome og Principe', 5623: 'Salomonøerne', 
                 5625: 'Skt. Kitts og Nevis', 5700: 'Rusland', 5704: 'Ukraine', 
                 5706: 'Hviderusland', 5708: 'Armenien', 5710: 'Aserbajdsjan', 
                 5712: 'Moldova', 5714: 'Usbekistan', 5716: 'Kasakhstan', 
                 5718: 'Turkmenistan', 5720: 'Kirgisistan', 5722: 'Tadsjikistan', 
                 5724: 'Georgien', 5750: 'Kroatien', 5752: 'Slovenien', 
                 5754: 'Bosnien-Hercegovina', 5756: 'Makedonien', 5757: 'Serbien', 
                 5758: 'Jugoslavien, Forbundsrepublikken', 5759: 'Montenegro', 
                 5761: 'Kosovo', 5776: 'Tjekkiet', 5778: 'Slovakiet', 5779: 'Cookøerne', 
                 5800: 'Land ukendt (2)', 5901: 'Færøerne uoplyst', 5902: 'Færøerne', 
                 5999: 'Land ukendt (1)'}

In [ ]:
# unique years in the dataset:
# x = year, 
unique_years = np.unique(dd[:,0]) # all yś where x is index 0 (which is year)
unique_years

In [ ]:
# dataset is [year=0, age=1, area=2, nationality=3, amount=4]

# unique nationalities/citizenships:
c_keys = np.unique(dd[:,3]) #tag alle nationaliteter 
c_keys = c_keys[c_keys != 5100] #remove danish citizens
#print(c_keys)
mask_year_2012 = dd[:,0] == 2012
mask_swedish = dd[:,3] == 5120

#SUM all the swedish people in 2012
np.sum(dd[(mask_year_2012) & (mask_swedish)][:,4])


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children were 0 years old in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [ ]:
%%bash
head befkbhalderstatkode.csv

In [ ]:
import numpy as np

filename = './befkbhalderstatkode.csv'
bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)

In [ ]:
#0 år gamle, tyske børn i 2015

import numpy as np

bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
dd = bef_stats_df

print(dd[1,0])

mask = ((dd[:,0] == 2015)   & (dd[:,2] == 40)  &  (dd[:,3] == 5180)) 
#print(dd[mask])
smallGermans = dd[mask]
#print(smallGermans[:,4].sum())

In [ ]:
#tag forskellige input

def number_of_people(year=None, area=None, age=None, nationality=None):    
    ddYear = dd[dd[:,0] == year]
    ddArea = ddYear[ddYear[:,1] == area]
    
    if age == None:
        ddNat = ddYear[ddYear[:,3] == nationality]  
    else:
        ddAge = ddArea[ddArea[:, 2] == age]
        ddNat = ddAge[ddAge[:,3] == nationality]  
    
    #ddAge = ddArea[ddArea[:, 2] == age]
    #ddNat = ddAge[ddAge[:,3] == nationality]     
        
    sum_of_people = ddNat[:,4].sum() 
    return ddNat, sum_of_people

french_mask = (dd[:,0] == 2015) & (dd[:,2] == 30) & (dd[:,3] == 5130)
german_mask = (dd[:,0] == 2011) & (dd[:,3] == 5180)

print(number_of_people(1999, 2, 5180))


In [ ]:
def number_of_people(year, area, age, nationality):
    ddYear = dd[dd[:,0] == year]
    ddArea = ddYear[ddYear[:,1] == area]
    
    if age == 0:
        ddAge = ddArea[ddArea[:,2]]
    else:
        ddAge = ddArea[ddArea[:,2] == age]
        
    ddNat = ddAge[ddAge[:,3] == nationality]     
        

In [ ]:
# create a set of conuntry codes with people living in Copenhagen
c_keys = np.unique(dd[:,3])
# we are interested in non-danes only
c_keys = c_keys[c_keys != 5100]
print('all the country keys:\n',c_keys)
# and again we only consider 2015
mask_year_2015 = (dd[:,0] == 2015)

number_per_citizen_group = np.array([np.sum(dd[mask_year_2015 & (dd[:,3] == c_code)][:,4]) for c_code in c_keys])
print('all the number of people in each citizen group:\n',number_per_citizen_group)
idx_of_largest_group = np.argmax(number_per_citizen_group)
print('index (or indices if more) of the largest group: ',idx_of_largest_group)
county_code = c_keys[idx_of_largest_group] # using the index of the largest summed up group and finding the value of that index in another slice of the same dataset
print('c_k:',county_code)
country_name = country_codes[county_code] # this is a dictionary where key=country_code and value=country name
print('country_name: ',country_name)
print(f'{number_per_citizen_group.max()} inhabitants come from {country_name}')

In [ ]:
no_per_c_sorted = sorted(np.copy(number_per_citizen_group))
sorted?
print(no_per_c_sorted)
print('.------------------------------------------------------------------------------------------')
print(np.where(number_per_citizen_group==no_per_c_sorted[-1]))
snd_max_idx = np.where(number_per_citizen_group==no_per_c_sorted[-1])[0][0] # [0][0] from ndarray to array to scalar
print(snd_max_idx)
#no_per_c[no_per_c == no_per_c_orig[-2]][0]
country_codes[c_keys[snd_max_idx]]

In [4]:
def transformByMaks(data, mask):
    """
    arg1 is the dataset on the form [[year, area, age, nationality, amount]]
    arg2 is the mask on the form data[:,3] == 5120 to find swedish or data[:,0] == 1999 to filter on year
    returns a new numpy array with the filtered data.
    """
    return data[mask]

def getDataByX(data, x_value):
    params = {'year':0, 'area':1, 'age':2, 'nationality': 3}
    x = params[x_value]
    return {year:np.sum(data[:,4]) for year in np.unique(data[x])}
    
mask = (dd[:,2] == 18) & (dd[:,3] == 5100)
result = transformByMaks(dd, mask)
print(result)
print(getDataByX(result, 'year'))

NameError: name 'dd' is not defined

### Computing a Histogram Concisely

As said, we are using NumPy to express our data queries more concisely. The first three lines of the following program compute the histogram of ages in 2015. That is, in three lines we can express the same as in the 13 lines of , see the function `get_population_stat` under *Bar Plots* in *14-Intro to Plotting*.

In [ ]:
import matplotlib.pyplot as plt
mask = (dd[:,0] == 2015)
set_of_ages = np.unique(dd[mask][:,2])
freq_ages = np.array([np.sum(dd[mask & (dd[:,2] == age)][:,4]) #summen af hver aldersgruppe i 2015
                      for age in set_of_ages])

plt.bar(set_of_ages, freq_ages)


And computing the increase of foreign population from 2014 to 2015 is similarly easy. Read and explain the following program.

In [ ]:
mask = (dd[:,3] != 5100)
sum_14 = np.sum(dd[(dd[:,0] == 2014) & mask][:,4]) #antallet af ikke-danskere i 2014
sum_15 = np.sum(dd[(dd[:,0] == 2015) & mask][:,4]) #antallet af ikke-danskere i 2015

plt.axis([2013, 2016, 0, max([sum_14, sum_15]) + 2000])
plt.bar([2014, 2015], [sum_14, sum_15], width=0.8,  align='center')
plt.xticks([2014, 2015])
plt.ticklabel_format(useOffset=False)

## class exercise: extracting
Based on the Copenhagen population data do the following (not including danish citizens):
1. Find the 10 largest population groups
2. Find the 10 largest population groups of children (0-17 y.o.) 
3. Create a barplot with the 10 largest groups on x-axis and 2 bars of both adult and children on y-axis
  - make one bar red and the other green
  - give them labels

# Self study: For what else can we use NumPy?

Images are just multi-dimensional arrays. For example, lets have a look at a small running Commander Keen

![keen](images/commander_keen.png)

With the following code we receive the image and convert it into a NumPy array so that we can inspect the image data.

In [ ]:
!wget https://16couleurs.files.wordpress.com/2014/01/commander_keen_sprite_run.gif?w=611

In [ ]:
%%bash
wget https://16couleurs.files.wordpress.com/2014/01/commander_keen_sprite_run.gif

In [ ]:
#### import webget
import numpy as np
from PIL import Image


im = Image.open('commander_keen_sprite_run.gif?w=611')
# convert the data to RGB color space
rgb_im = im.convert('RGB')
print(rgb_im)
im_array = np.asarray(rgb_im)
print(im_array.shape, ' represents the rows(y),columns(x) and pixelcolor (as rgb)')
print('255 255 255 is white to see other colors lets slice away the first 10 squares of data: \n\n',im_array[10:11,7:17,0:])
im_data = np.copy(im_array)  # we have to copy the data as we want to modify it later

Let's get a feeling for how colors are distributed in the image by plotting the values per color channel.

In [ ]:
# import matplotlib.pyplot as plt
print('im_data.shape[0] is the y-values (verical dimension):\n',im_data.shape[0],'\nim_data.shape[1] is the x-values (horizontal dimension):\n',im_data.shape[1],'\nim_data.shape[2] is the actual rgb color of the pixel:\n',im_data.shape[2])
img_line = im_data.reshape(im_data.shape[0] * im_data.shape[1], im_data.shape[2]) # reshaping 3d array to a 2d array by putting the x,y values one long data row
print('now its a 2d array:\n',img_line)
print('new shape: ',img_line.shape)
plt.plot(img_line[:,0], 'ro') #shorthand for red circle
plt.plot(img_line[:,1], 'gx') #green x
plt.plot(img_line[:,2], 'b+') #blue plus
plt.xlabel('Pixels starting from upper left corner')
plt.ylabel('strength of the r,g or b color in the pixel') # white color shows up as full force on all 3 chanels, but blue overpowers because it is written on top (last)
plt.show()

Replacing a set of RGB values can be done as in the following. We want to give Commander Keen another t-shirt color. So by querying the color at the central pixel `im_data[32,24,:]`, we see that it is `[252, 84, 252]`. Consequently, we find all pixels with these values and assign a new value to those positions.

In [ ]:
im_data_orig = np.copy(im_data)

In [ ]:
%matplotlib notebook
print(im_data.shape)
print(im_data_orig[32,24,:]) # pink color from 32px down - 24px right in commander_keen img

mask = (im_data_orig[:,:,0] == 252) & (im_data_orig[:,:,1] == 84) & (im_data_orig[:,:,2] == 252)
im_data[mask] = np.array([250, 230, 0]) # replace the pixels chosen by the mask with [250,230,0]=yellow
plt.figure()
plt.subplot(1, 2, 2) # 1=row, 2=column, 2=index (image will have one row with 2 columns AND this plot will be in the second column/index)
plt.title('Original')
plt.imshow(im_data_orig)
plt.subplot(1, 2, 1)
plt.title('Modified')
plt.imshow(im_data)
plt.show()

As you saw above, each channel for the RGB values is represented with the help of a two-dimensional array. We can split them up to inspect the respective intensities.

In [ ]:
%matplotlib inline
red_channel = im_data_orig[:,:,0] # red=0, green=1, blue=2
print('upper left corner is all white and red,green,blue==255:',red_channel[0,0],'\n somewhere in the center:',red_channel[50,24])
plt.imshow(red_channel, cmap=plt.cm.Greys) # low value becomes light and close to 255 becomes black.

In [ ]:
channels = [('Red', 0), ('Green', 1), ('Blue', 2)]
plt.figure()
for channel, channel_idx in channels:
    plt.subplot(1, 3, channel_idx+1)
    plt.title('{}'.format(channel))
    imarray = im_data_orig[:,:,channel_idx]
    plt.imshow(imarray, cmap=plt.cm.Greys)

In [ ]:
%%bash
head befkbhalderstatkode.csv

In [ ]:
filename = './befkbhalderstatkode.csv'

dd = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

neighb = {1: 'Indre By', 2: 'Østerbro', 3: 'Nørrebro', 4: 'Vesterbro/Kgs. Enghave', 
       5: 'Valby', 6: 'Vanløse', 7: 'Brønshøj-Husum', 8: 'Bispebjerg', 9: 'Amager Øst', 
       10: 'Amager Vest', 99: 'Udenfor'}

def number_of_people_in_area(n, data):
    all_people_in_given_n = data[data[:,1] == n]
    sum_of_people = all_people_in_given_n[:,4 ].sum()
    return sum_of_people

allPeopleAreas = np.array([number_of_people_in_area(n, dd) for n in neighb.keys()])

allAreas = neighb.values()

plt.figure(figsize=(19,10))
plt.bar(allAreas, allPeopleAreas)